[package]
name = "test-try"
version = "0.1.0"
edition.workspace = true

[dependencies]
test-try-macros = "0.1"

[lints]
workspace = true

[dev-dependencies]
derive_more = { version = "2", features = ["error", "display", "from"] }
anyhow = { version = "1" }
